title: Kendall Nodorft
description: Designer & Creator
site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: kendallnodorft
email: kendallnodorft@gmail.com


# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
